# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]


permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run python on file looking for file name
      run: |
        ls -ltr
        
    - name: Get changed folders
      run: |
        echo "Fetching changed directories..."
        git fetch --depth=2 # Ensure we have the previous commit
        CHANGED_FOLDERS=$(git diff --name-only HEAD^ HEAD | awk -F'/' '{print $0}' | sort -u)
        echo "Changed folders:"
        for file in $CHANGED_FOLDERS; do
          echo "processing file: $file"
          DIR_NAME=$(echo "$file" | cut -d'/' -f1)
          OTHERDIR=$(echo "$file" | cut -d'/' -f2)
          if [[ "$DIR_NAME" == *obsidian_notes* ]]; then
            echo "$DIR_NAME/$OTHERDIR"
            cp "exportMdFileToHtml.py" "$DIR_NAME/$OTHERDIR/exportMdFileToHtml.py" || exit 1
            cd "$DIR_NAME/$OTHERDIR" || exit 1
            python3 exportMdFileToHtml.py index.md y y
            rm -r exportMdFileToHtml.py
          fi
        done

